### ISSUE TITLE
KeyError: 'my_program'

### ISSUE THREAD

**Issue by sanjok-bless** [bendikro/supervisord-dependent-startup#7]
A have an error in my /var/log/supervisor/dependentstartup-stderr---supervisor-ACKKwh.log:

```
2019-10-07 15:17:49,697 - supervisord_dependent_startup - [INFO   ]
2019-10-07 15:17:49,697 - supervisord_dependent_startup - [INFO   ] supervisord-dependent-startup event listener starting...
2019-10-07 15:17:49,699 - supervisord_dependent_startup - [INFO   ] Connected to supervisor with API version: 3.0
2019-10-07 15:17:49,700 - supervisord_dependent_startup - [INFO   ] Reading supervisor config: /etc/supervisor/supervisord.conf
2019-10-07 15:17:49,702 - supervisord_dependent_startup - [INFO   ]
2019-10-07 15:17:49,702 - supervisord_dependent_startup - [INFO   ]
2019-10-07 15:17:49,704 - supervisord_dependent_startup - [INFO   ]  - my_program_updater  state: BACKOFF    dependent_startup: False
2019-10-07 15:17:49,704 - supervisord_dependent_startup - [ERROR  ] Error occured:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/supervisord_dependent_startup/supervisord_dependent_startup.py", line 738, in run
    main()
  File "/usr/local/lib/python3.5/dist-packages/supervisord_dependent_startup/supervisord_dependent_startup.py", line 732, in main
    event_listener.run_and_listen()
  File "/usr/local/lib/python3.5/dist-packages/supervisord_dependent_startup/supervisord_dependent_startup.py", line 657, in run_and_listen
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/supervisord_dependent_startup/supervisord_dependent_startup.py", line 661, in run
    self.services_handler.update_proc_info_all(print_services_list=True)
  File "/usr/local/lib/python3.5/dist-packages/supervisord_dependent_startup/supervisord_dependent_startup.py", line 489, in update_proc_info_all
    self.log_services_list()
  File "/usr/local/lib/python3.5/dist-packages/supervisord_dependent_startup/supervisord_dependent_startup.py", line 513, in log_services_list
    log.info(" - %s" % self.get_service_str(service.name))
  File "/usr/local/lib/python3.5/dist-packages/supervisord_dependent_startup/supervisord_dependent_startup.py", line 497, in get_service_str
    state = self.get_service_state(name)
  File "/usr/local/lib/python3.5/dist-packages/supervisord_dependent_startup/supervisord_dependent_startup.py", line 373, in get_service_state
    return self.proc_info[name].get('statename')
KeyError: 'my_program'
```

supervisord.conf:
```
; supervisor config file

[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[supervisord]
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor            ; ('AUTO' child log dir, default $TEMP)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

; The [include] section can just contain the "files" setting.  This
; setting can list multiple files (separated by whitespace or
; newlines).  It can also contain wildcards.  The filenames are
; interpreted as relative to this file.  Included files *cannot*
; include files themselves.

[eventlistener:dependentstartup]
command=python3 -m supervisord_dependent_startup
autostart=true
autorestart=unexpected
startretries=0
exitcodes=0,3
events=PROCESS_STATE

[include]
files = /etc/supervisor/conf.d/*.conf
```

And /etc/supervisor/conf.d/my.conf:
```
[program:my_program_updater]
directory=/home/dr/my/server
command=sh -c '/home/dr/my/venv/bin/python -m updater.run'
process_name=my_updater
autostart=true
autorestart=false
startretries=1
redirect_stderr=true
stderr_logfile=/home/dr/my/dr_updater.err.log
stdout_logfile=/home/dr/my/dr_updater.out.log

[program:my_master]
command=/home/dr/my/venv/bin/python /home/dr/my/server/main.py --port=8888 --standalone=True --is_master=True
process_name=my_server_master
autostart=false
autorestart=true
redirect_stderr=true
stderr_logfile=/home/dr/my/dr_server_master.err.log
stdout_logfile=/home/dr/my/dr_server_master.out.log
dependent_startup=true
dependent_startup_wait_for=my_updater:exited,fatal
```

What am I doing wrong?

**Comment by bendikro** [comment]
The problem is the line `process_name=my_server_master` which changes the process name from `my_master` set in the header `[program:my_master]`. If you remove that line it should work. This is a bug in `supervisord-dependent-startup`.

**Comment by bendikro** [comment]
@sanjok-bless I've made a new release which solves this issue
